### ISSUE TITLE
error code in rrdb client lib cannot compile on windows

### ISSUE THREAD

**Issue by imzhenyu** [imzhenyu/rocksdb#10]
e.g., for

``` C++
ERROR_CODE(ERROR_TIMEOUT,               -2,     "timeout");
```

Since ERROR_TIMEOUT is already defined in windows header files, i.e. 

``` C++
#define ERROR_TIMEOUT                    1460L
```

This won't compile. Let's fix it as using special names instead.

**Comment by imzhenyu** [comment]
@xiaotz @qinzuoyan please take a look.

**Comment by qinzuoyan** [comment]
I have built rDSN on windows, but I could not found how to install rDSN to DSN_ROOT, and how to build rocksdb. What the step?

**Comment by imzhenyu** [comment]
simply use `run build RelWithDebInfo .\buildrel install` to build and install rDSN to DSN_ROOT; 
use cmake to build rrdb and it will automatically find the libs under DSN_ROOT\lib.

**Comment by qinzuoyan** [comment]
I have run `run build RelWithDebInfo .\buildrel install` successfully, and the outputs are installed to "C:\Program Files\dsn", but I found the env DSN_ROOT is not properly set, should I set it manually?

**Comment by imzhenyu** [comment]
you can always run `run.cmd setup-env` to reset the DSN_ROOT.

**Comment by mcfatealan** [comment]
@qinzuoyan @imzhenyu is this issue fixed yet? I met same compiling error today on windows. It shows that some error codes have duplicate names with winerror.h

**Comment by qinzuoyan** [comment]
@mcfatealan , not fixed yet. I am trying to fix it, would you please tell me how to build rrdb on windows? I have built and installed rDSN.

**Comment by mcfatealan** [comment]
@qinzuoyan thanks for the extra info. I tried to build it using the following commands:

```
mkdir builder
cd D:\rocksdb\builder
cmake .. -G "Visual Studio 14 2015 Win64"  -DBOOST_INCLUDEDIR="D:\rDSN\ext\boost_1_59_0" -DBOOST_LIBRARYDIR="D:\rDSN\ext\boost_1_59_0\lib64-msvc-14.0"
```

Then open the generated VS project file (rrdb.sln) to build the target.

**Comment by qinzuoyan** [comment]
@mcfatealan , fixed now, refer to https://github.com/imzhenyu/rocksdb/commit/0840af64320213b52597b3a06b98b1a8d47eb422

**Comment by mcfatealan** [comment]
@qinzuoyan  Thanks!
