### ISSUE TITLE
apply checkpoint failure

### ISSUE THREAD

**Issue by imzhenyu** [imzhenyu/rocksdb#4]
// load checkpoint meta info, and assign decrees
                dassert(ci.seq == _last_seq, 
                    "seq numbers from loaded data and attached meta info do not match: %" PRId64 " vs %" PRId64 "",
                    ci.seq,
                    _last_seq
                    );

**Comment by imzhenyu** [comment]
@qinzuoyan seems introduced by last change. would you please take a look into this?

**Comment by imzhenyu** [comment]
triggered by running vtest. seems easy to re-produce.

e:\rocksdb\buildsln\bin\rrdb\Debug>findstr /I /S /C:"assertion" log.*.txt
test-1\log.36.txt:F05:54:34.231 (1449726874231338500 26a0) replica1.THREAD_POOL_REPLICATION_LONG1.040300010002a4c0: assertion expression: ci.seq == _last_seq
test-1\log.40.txt:F06:00:34.381 (1449727234381232400 3c64) replica2.THREAD_POOL_REPLICATION_LONG0.05030001000346e8: assertion expression: ci.seq == _last_seq
test-10\log.46.txt:F06:01:12.275 (1449727272275837500 be54) replica1.THREAD_POOL_REPLICATION_LONG1.04030001000385db: assertion expression: ci.seq == _last_seq
test-10\log.47.txt:F06:03:42.416 (1449727422416390000 b7a0) replica2.THREAD_POOL_REPLICATION_LONG0.0503000100037bc0: assertion expression: ci.seq == _last_seq
test-11\log.52.txt:F06:07:30.512 (1449727650512837500 bc1c) replica1.THREAD_POOL_REPLICATION_LONG1.040300010003a3ca: assertion expression: ci.seq == _last_seq
test-12\log.48.txt:F06:04:41.058 (1449727481058052900 9ef8) replica2.THREAD_POOL_REPLICATION_LONG1.050300010003be0c: assertion expression: ci.seq == _last_seq
test-12\log.49.txt:F06:05:31.171 (1449727531171493100 bdfc) replica1.THREAD_POOL_REPLICATION_LONG1.040300010003996a: assertion expression: ci.seq == _last_seq
test-14\log.44.txt:F05:57:34.863 (1449727054863222700 5c28) replica1.THREAD_POOL_REPLICATION_LONG0.0403000100032596: assertion expression: ci.seq == _last_seq
test-14\log.46.txt:F06:00:44.954 (1449727244954737200 56b0) replica2.THREAD_POOL_REPLICATION_LONG1.050300010003517a: assertion expression: ci.seq == _last_seq
test-15\log.41.txt:F05:58:42.414 (1449727122414197400 58b0) replica1.THREAD_POOL_REPLICATION_LONG0.040300010002f3ae: assertion expression: ci.seq == _last_seq
test-15\log.44.txt:F06:04:32.839 (1449727472839736500 0914) replica2.THREAD_POOL_REPLICATION_LONG0.05030001000372d6: assertion expression: ci.seq == _last_seq
test-16\log.42.txt:F05:58:15.260 (1449727095260938200 92a4) replica1.THREAD_POOL_REPLICATION_LONG0.040300010002e84a: assertion expression: ci.seq == _last_seq
test-16\log.42.txt:F05:58:35.169 (1449727115169019000 c2d8) replica2.THREAD_POOL_REPLICATION_LONG0.0503000100034df0: assertion expression: ci.seq == _last_seq
test-17\log.45.txt:F06:06:38.822 (1449727598822138500 2dd8) replica1.THREAD_POOL_REPLICATION_LONG1.0403000100035d99: assertion expression: ci.seq == _last_seq
test-17\log.46.txt:F06:07:38.039 (1449727658039644600 9bc4) replica2.THREAD_POOL_REPLICATION_LONG1.0503000100038702: assertion expression: ci.seq == _last_seq
test-18\log.46.txt:F05:59:30.043 (1449727170043425200 96f4) replica2.THREAD_POOL_REPLICATION_LONG1.05030001000343ef: assertion expression: ci.seq == _last_seq
test-18\log.46.txt:F06:00:29.846 (1449727229846536200 a708) replica1.THREAD_POOL_REPLICATION_LONG0.040300010003882a: assertion expression: ci.seq == _last_seq
test-19\log.47.txt:F06:04:34.919 (1449727474919975700 5890) replica1.THREAD_POOL_REPLICATION_LONG1.0403000100039fa9: assertion expression: ci.seq == _last_seq
test-19\log.48.txt:F06:06:45.081 (1449727605081070200 6974) replica3.THREAD_POOL_REPLICATION_LONG1.0603000100037b3a: assertion expression: ci.seq == _last_seq
test-20\log.47.txt:F06:00:40.061 (1449727240061565600 2a48) replica1.THREAD_POOL_REPLICATION_LONG0.0403000100039fd6: assertion expression: ci.seq == _last_seq
test-20\log.47.txt:F06:01:50.176 (1449727310176127500 5d20) replica2.THREAD_POOL_REPLICATION_LONG1.0503000100037d9f: assertion expression: ci.seq == _last_seq
test-3\log.41.txt:F05:56:32.933 (1449726992933616600 c440) replica2.THREAD_POOL_REPLICATION_LONG1.050300010002ca4b: assertion expression: ci.seq == _last_seq
test-3\log.42.txt:F05:59:03.855 (1449727143855004100 6760) replica1.THREAD_POOL_REPLICATION_LONG0.040300010003650b: assertion expression: ci.seq == _last_seq
test-4\log.41.txt:F05:58:06.323 (1449727086323205500 7b8c) replica1.THREAD_POOL_REPLICATION_LONG1.040300010003109b: assertion expression: ci.seq == _last_seq
test-4\log.41.txt:F05:58:36.028 (1449727116028476700 66f0) replica3.THREAD_POOL_REPLICATION_LONG1.060300010003183e: assertion expression: ci.seq == _last_seq
test-5\log.36.txt:F05:54:07.140 (1449726847140140000 b7bc) replica2.THREAD_POOL_REPLICATION_LONG1.0503000100029a9b: assertion expression: ci.seq == _last_seq
test-6\log.43.txt:F05:57:45.210 (1449727065210830800 6910) replica2.THREAD_POOL_REPLICATION_LONG0.0503000100034e7c: assertion expression: ci.seq == _last_seq
test-6\log.45.txt:F06:00:45.257 (1449727245257536600 a75c) replica1.THREAD_POOL_REPLICATION_LONG1.04030001000351c1: assertion expression: ci.seq == _last_seq
test-7\log.52.txt:F06:08:40.989 (1449727720989222400 7a24) replica2.THREAD_POOL_REPLICATION_LONG0.0503000100038c7d: assertion expression: ci.seq == _last_seq
test-8\log.49.txt:F06:03:34.420 (1449727414420764700 82e0) replica2.THREAD_POOL_REPLICATION_LONG0.050300010003abc8: assertion expression: ci.seq == _last_seq
test-8\log.52.txt:F06:07:02.130 (1449727622130330200 b9a0) replica1.THREAD_POOL_REPLICATION_LONG0.04030001000412d6: assertion expression: ci.seq == _last_seq

**Comment by qinzuoyan** [comment]
ok

**Comment by qinzuoyan** [comment]
I have reproduced the problem, and will trace and fix it.

**Comment by imzhenyu** [comment]
Cool~
